src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\String\Slugger\AsciiSlugger;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 4095, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $price = null;

    #[ORM\Column]
    private ?int $available_quantity = null;

    #[ORM\Column]
    private ?bool $visible = null;

    private AsciiSlugger $slugger;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getAvailableQuantity(): ?int
    {
        return $this->available_quantity;
    }

    public function setAvailableQuantity(int $available_quantity): self
    {
        $this->available_quantity = $available_quantity;

        return $this;
    }

    public function isVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(bool $visible): self
    {
        $this->visible = $visible;

        return $this;
    }

    public function getSlug(): string
    {
        $this->slugger = new AsciiSlugger();
        
        return $this->slugger->slug($this->getName())->lower()->toString();
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $username = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class)
            ->add('description', TextareaType::class)
            ->add('price', MoneyType::class, [
                "divisor" => 100
            ])
            ->add('available_quantity', IntegerType::class)
            ->add('visible', CheckboxType::class, [
                "required" => false
            ])
            ->add('submit', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;

class HomeController extends AbstractController
{
    public function show(): Response
    {
        return $this->render("home.html.twig");
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\ProductType;
use App\Repository\ProductRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class ProductController extends AbstractController
{
    private ManagerRegistry $manager_regitstry;
    private ProductRepository $product_repository;

    public function __construct(ManagerRegistry $manager_regitstry)
    {
        $this->manager_regitstry = $manager_regitstry;
        $this->product_repository = $manager_regitstry->getRepository(Product::class);
    }

    public function list(): Response
    {
        $products = $this->product_repository->findAllAvailable();
        
        return $this->render("product.list.html.twig", [
            "section" => "products",
            "products" => $products
        ]);
    }

    public function show(): Response
    {
        return $this->render("product.show.html.twig", [
            "section" => "products"
        ]);
    }


    public function adminList(): Response
    {   
        $products = $this->product_repository->findAll();

        return $this->render("admin.product.list.html.twig", [
            "section" => "products",
            "products" => $products
        ]);
    }

    public function adminAdd(Request $request): Response
    {
        $product = new Product();
        
        $form = $this->createForm(ProductType::class, $product);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $product = $form->getData();

            $this->product_repository->save($product, true);

            return $this->redirectToRoute('admin.product.list');
        }

        return $this->render("admin.product.add.html.twig", [
            "section" => "products",
            "form" => $form->createView()
        ]);
    }

    public function adminEdit(Request $request, int $id): Response
    {
        $product = $this->product_repository->find($id);
        
        $form = $this->createForm(ProductType::class, $product);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $product = $form->getData();

            $this->product_repository->save($product, true);

            return $this->redirectToRoute('admin.product.list');
        }

        return $this->render("admin.product.edit.html.twig", [
            "section" => "products",
            "form" => $form->createView()
        ]);
    }

    public function adminDelete(int $id): Response
    {   
        $product = $this->product_repository->find($id);

        $this->product_repository->remove($product, true);
        
        return $this->redirectToRoute('admin.product.list');
    }
}

templates/admin.product.add.html.twig
{% form_theme form 'bootstrap_5_layout.html.twig' %}

{% extends "admin_base.html.twig" %}

{% block content %}
    <h1>Ajouter un produit</h1>
    {{ form(form) }}
{% endblock %}

templates/admin.product.edit.html.twig
{% form_theme form 'bootstrap_5_layout.html.twig' %}

{% extends "admin_base.html.twig" %}

{% block content %}
    <h1>Modifier un produit</h1>
    {{ form(form) }}
{% endblock %}

templates/admin.product.list.html.twig
{% extends "admin_base.html.twig" %}

{% block content %}
    <h1>Produits</h1>

    <div class="row row-cols-1 row-cols-md-3 g-4">

        {% for product in products %}
            <div class="col">
                <div class="card">
                    <img src="/ressources/samples/candle.png" class="card-img-top" alt="Test">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">{{ product.description }}</p>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">{{ (product.price/100)|format_currency("EUR", locale="fr") }}</li>
                            <li class="list-group-item">
                                {% if product.availableQuantity > 0 %}
                                    <span class="badge text-bg-success">{{ product.availableQuantity }} en stock</span>
                                {% else %}
                                    <span class="badge text-bg-danger">0 en stock</span>
                                {% endif %}
                                {% if product.isVisible %}
                                    <span class="badge text-bg-primary">Visible</span>
                                {% else %}
                                    <span class="badge text-bg-secondary">Invisible</span>
                                {% endif %}
                            </li>
                            <li class="list-group-item">
                                <div class="btn-group d-flex justify-content-center" role="group">
                                    <a href="{{ url('admin.product.edit', {'id': product.id}) }}" class="btn btn-secondary">Modifier</a>
                                    <a href="{{ url('admin.product.delete', {'id': product.id}) }}" class="btn btn-outline-danger">Supprimer</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <hr>

    <a href="{{ url('admin.product.add') }}" class="btn btn-primary">Ajouter</a>

{% endblock %}

templates/admin_base.html.twig
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/ressources/logo.svg" type="image/x-icon">
    <title>Piwalika Admin</title>

    {% block extra_css %}{% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{{ url('home') }}">Piwalika</a>
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a {{ (section == 'products') ? 'class="nav-link active"' : 'class="nav-link"'}} href="{{ url("admin.product.list") }}">Produits</a>
          </li>
          <li class="nav-item">
            <a {{ (section == 'test') ? 'class="nav-link active"' : 'class="nav-link"'}} href="{{ url("admin.product.list") }}">Test</a>
          </li>
          <li class="nav-item">
            <a {{ (section == 'test') ? 'class="nav-link active"' : 'class="nav-link"'}} href="{{ url("admin.product.list") }}">Test</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container py-5">
      {% block content %}{% endblock %}
    </div>

    {% block extra_js %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.6.3.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
  </body>
</html>

templates/base.html.twig
<!DOCTYPE html>
<html lang="fr_fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/stylesheets/style.css">
    {% block extra_css %}{% endblock %}
    <link rel="shortcut icon" href="/ressources/logo.svg" type="image/x-icon">
    <title>Piwalika</title>
</head>
<body>
    <header class="header transparent-header" id="header">
        <ul class="header-sections-nav">
            <li><a class="nav-button" href="{{ url('home') }}">Accueil</a></li>
            <li><a class="nav-button" href="{{ url('product.list') }}">Produits</a></li>
            <li><a class="nav-button" href="{{ url('home') }}">Actualités</a></li>
            <li><a class="nav-button" href="{{ url('home') }}">À propos</a></li>
        </ul>

        {#<ul class="header-account-nav">
            {% if app.user %}
                <li><a class="nav-button highlighted-nav-button" href="{{ none }}">{{ app.user.username }}</a></li>
                <li><a class="nav-button" href="{{ url('log_out') }}">{{ 'navbar.log_out'|trans|u.title }}</a></li>
            {% else %}
                <li><a class="nav-button highlighted-nav-button" href="{{ url('log_in') }}">{{ 'navbar.log_in'|trans|u.title }}</a></li>
            {% endif %}
        </ul>#}
    </header>

    <main id="content">
        {% block content %}{% endblock %}
    </main>

    <script src="/scripts/navbar.js"></script>
    {% block extra_js %}{% endblock %}

</body>
</html>

templates/home.html.twig
{% extends "base.html.twig" %}

{% block content %}
    <div class="parallax-section parallax-section-overlay section-separator" style="background-image:url(/ressources/samples/background_{{ random(1, 4) }}.jpg);">
        <div class="parallax-section-header"></div>
        <div class="parallax-section-content">
        <object class="welcome-logo" data="/ressources/logo.svg" type="image/svg+xml"></object>
            <p class="welcome-text">
                Bougies parfumées et galets fondants à base de cire végétale aux parfums de Grasse
            </p>
        </div>
    </div>
        
    <div class="section section-separator">
        Test
    </div>

    <div class="parallax-section section-separator" style="background-image:url(/ressources/samples/detail.jpg);">
    </div>

    <div class="section">
        Test
    </div>
{% endblock %}

templates/product.list.html.twig
{% extends "base.html.twig" %}

{% block content %}
    <div class="header-spacer">
    </div>

    <div class="section">
        <ul class="section-container product-grid">
            {% for product in products %}
            <a href="{{ url('product.show', {slug:product.slug, id:product.id}) }}">
                <li class="thumbnail-frame">
                    <div class="thumbnail-frame-picture"><img src="/ressources/samples/candle.png" alt="{{ product.name }} image"></div>
                    <div class="thumbnail-frame-info">
                        <div class="thumbnail-frame-title">{{ product.name }}</div>
                        <div class="thumbnail-frame-price">{{ (product.price/100)|format_currency("EUR", locale="fr") }}</div>
                    </div>
                </li>
            </a>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/product.show.html.twig
{% extends "base.html.twig" %}

{% block content %}
    <div class="header-spacer">
    </div>

    <div class="section">
        <div class="section-container product-details">
            <div class="product-details-picture"><img src="/ressources/samples/candle.png" alt="Test"></div>
            <div class="product-details-title">Petite bougie parfumée Bonbon Mandarine</div>

            <div class="product-details-info">
                <div class="product-details-price">10,00 €</div>
                <div class="product-details-quantity-available in-stock">3 en stock</div>
            </div>

            <div class="product-details-actions">
                <div class="quantity-counter" id="quantity-counter">
                    <div class="quantity-counter-plus" id="plus">+</div>
                    <div class="quantity-counter-number" id="number">1</div>
                    <div class="quantity-counter-minus" id="minus">-</div>
                </div>

                <a class="product-details-action-add-to-cart">Ajouter au panier</a>
                <a class="product-details-action-buy">Acheter</a>
            </div>

            <div class="product-details-description">
                Petite bougie parfumée Bonbon Mandarine
            </div>
        </div>
    </div>
{% endblock %}